import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
      test.setTimeout(200000);

  await page.goto('http://localhost:8080/');
  await page.getByRole('button', { name: 'Alpine_Parts_Report_Prod' }).click();
  await page.getByRole('menuitem', { name: 'Alpine_20_KPI_Report_Prod' }).click();
  await page.locator('iframe').contentFrame().getByRole('img', { name: 'New GDCN' }).click();
  await page.locator('iframe').contentFrame().getByText('GDCN Backlog History', { exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Calendar button - choose date' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: '4', exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Calendar button - choose date' }).nth(1).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Previous month' }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: '29' }).nth(1).click();
  await page.locator('iframe').contentFrame().locator('.noUi-handle.noUi-handle-upper > .noUi-touch-area').click();
  await page.locator('iframe').contentFrame().getByText('Calendar button - choose dateCalendar button - choose date').click();
  await page.locator('iframe').contentFrame().locator('.cdk-overlay-backdrop').click();
  await page.locator('iframe').contentFrame().locator('.noUi-handle.noUi-handle-upper > .noUi-touch-area').click();
  await page.locator('iframe').contentFrame().locator('.date-slicer-slider').click();
  await page.locator('iframe').contentFrame().locator('.noUi-connect').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Start date. Available input' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Start date. Available input' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Start date. Available input' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Start date. Available input' }).fill('7/16/2025');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).fill('10/29/2025');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).fill('7/29/2025');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End date. Available input' }).press('Enter');
  await page.locator('iframe').contentFrame().locator('.cdk-overlay-backdrop').click();
  await page.locator('iframe').contentFrame().getByText('GDCN Backlog History By Status').click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Anaheim' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Anaheim' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Santa Clara' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Santa Clara' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Backlog Weekly Comparison' }).click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '/8/2025' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '/11/2025' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').getByText('1/11/').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '/4/2025' }).dblclick();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'GDCN Weekly Delta' }).click();
  await page.locator('iframe').contentFrame().getByText('Multiple Submits').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'GDCN Weekly Delta' }).click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'ORG' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'ORG' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'SCL' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'SCL' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Calendar button - choose date' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: '11' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Multiple Submits' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Start', exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Start', exact: true }).fill('3');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Start', exact: true }).press('Enter');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End', exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End', exact: true }).fill('12');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'End', exact: true }).press('Enter');
  await page.locator('iframe').contentFrame().locator('.noUi-connect').first().click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Daily Quote Logs Brad' }).click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Facility' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Facility' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Priority' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'PackageName' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'PackageName' }).click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Completed' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Completed' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Priority' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.getByRole('button', { name: 'Alpine_20_KPI_Report_Prod' }).click();
  await page.getByRole('menuitem', { name: 'FAE_KPI_Report' }).click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View New').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View New').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View EOD').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View New').click();
  await page.getByRole('button', { name: 'FAE_KPI_Report' }).click();
  await page.getByRole('menuitem', { name: 'Alpine_20_KPI_Report_Prod' }).click();
  await page.getByRole('button', { name: 'Alpine_20_KPI_Report_Prod' }).click();
  await page.getByRole('menuitem', { name: 'FAE_KPI_Report' }).click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View New').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View EOD').click();
  await page.locator('iframe').contentFrame().getByTestId('filter-btn').getByText('Filters').click();
  await page.locator('iframe').contentFrame().getByTestId('filter-btn').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Daily FAE Metrics' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Daily FAE Employee Report' }).click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Ben Norris' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Ben Norris' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Filomeno Ponce' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Filomeno Ponce' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Ben Norris' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View New').click();
  await page.locator('iframe').contentFrame().getByTestId('slicer-dropdown').locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Brad Banister' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Filomeno Ponce' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('region', { name: 'Power BI Report' }).click();
  await page.locator('iframe').contentFrame().getByRole('region', { name: 'Power BI Report' }).click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View EOD').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark View New').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Daily FAE Employee Metrics' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'FAE Capture Rate By Customer' }).click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Quote', exact: true }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Part' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'FAE Capture Rate By Sales Rep' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'FAE Capture Rate By Customer' }).click();
  await page.getByRole('button', { name: 'FAE_KPI_Report' }).click();
  await page.getByRole('menuitem', { name: 'Sales Report' }).click();
  await page.getByRole('button', { name: 'Sales Report' }).click();
  await page.locator('html').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('region', { name: 'Power BI Report' }).click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Customer' }).locator('div').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: '4Front Solutions-Erie, PA' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Search').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Clear').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
  await page.locator('iframe').contentFrame().getByRole('gridcell', { name: '2,287' }).click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Customer' }).locator('div').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'A&M Electronics-Valencia, CA' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Search').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Quarter' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Clear').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Quarter' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Month' }).locator('div span').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Win Rate' }).click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Close').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Sales Summary' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'CSR Performance Metrics' }).click();
  await page.getByRole('button', { name: 'Sales Report' }).click();
  await page.getByRole('menuitem', { name: 'Quoting Throughput Report' }).click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Month' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Month' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Quarter' }).click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Quarter' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Quoter Throughput' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Data Entry Throughput' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Average Quotes Over Time' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Minutes Per Quote' }).click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Role' }).locator('div').click();
  await page.locator('iframe').contentFrame().getByRole('option', { name: 'Select all' }).click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Role' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Daily Breakdown', exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Approver Throughput / Average' }).click();
  await page.locator('iframe').contentFrame().getByRole('tab', { name: 'Approver Daily Breakdown' }).click();
  await page.getByRole('button', { name: 'Quoting Throughput Report' }).click();
  await page.getByRole('menuitem', { name: 'DailyQuoteReport - Alpine' }).click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Search').click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: 'Bookmark . Click here to' }).first().click();
  await page.locator('iframe').contentFrame().getByRole('combobox', { name: 'Pricer' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByText('Ben Norris').click();
  await page.locator('iframe').contentFrame().getByText('Ben Norris').click();
  await page.locator('iframe').contentFrame().getByText('Ben Norris').click();
  await page.locator('iframe').contentFrame().getByText('Press Enter to explore dataBookmark Clear').click();
  await page.getByRole('button', { name: 'DailyQuoteReport - Alpine' }).click();
  await page.locator('html').click();
});